### ISSUE TITLE
'bump' parses files other than package.xml

### ISSUE THREAD

**Issue by jacobperron** [audrow/update-ros-pkg-versions#3]
To reproduce, checkout https://github.com/ros/pluginlib (`ros2` branch), and run
```
update-ros-pkg-versions bump -t minor
```
I noticed it was complaining about this test file named `test_package.xml`: https://github.com/ros/pluginlib/blob/5c30f110a19c506f9e85ad03a0025090decaf2cf/pluginlib/test/test_package.xml

with the error:

```
error: Uncaught (in promise) Error: Version is not consistent - got the following versions: 2.2.0, 5.0.0
    throw new Error(
          ^
    at getVersion (file:///home/jacob/ws/update-ros-pkg-versions/src/file_system/index.ts:123:11)
    at async bumpFiles (file:///home/jacob/ws/update-ros-pkg-versions/src/file_system/index.ts:72:26)
    at async Object.bumpFn (file:///home/jacob/ws/update-ros-pkg-versions/src/index.ts:11:3)
    at async CAC.<anonymous> (file:///home/jacob/ws/update-ros-pkg-versions/src/cli/index.ts:62:7)
```

I guess the tool should only parse files with the exact name `package.xml`.

**Comment by audrow** [comment]
Good catch.
